"""
Router implementation for tw/router.

Provides server-side route resolution and Link component rendering.
The client-side SPA runtime is generated by runtime.py.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


@dataclass
class Route:
    """A route definition."""
    path: str
    page: str = ""
    dynamic: bool = False
    param_name: str = ""
    children: List["Route"] = field(default_factory=list)
    redirect: str = ""
    middleware: List[str] = field(default_factory=list)


class Router:
    """Server-side route resolver."""

    def __init__(self):
        self._routes: List[Route] = []
        self._compiled: List[Tuple[re.Pattern, Route]] = []

    def add(self, route: Route) -> None:
        self._routes.append(route)
        self._compile_route(route)

    def _compile_route(self, route: Route) -> None:
        """Convert a route path with params into a regex."""
        path = route.path
        # Convert [param] to named capture groups
        pattern = re.sub(r'\[([^\]]+)\]', r'(?P<\1>[^/]+)', path)
        pattern = '^' + pattern + '/?$'
        self._compiled.append((re.compile(pattern), route))

    def resolve(self, path: str) -> Optional[Tuple[Route, Dict[str, str]]]:
        """Resolve a URL path to a route and extract params."""
        for pattern, route in self._compiled:
            match = pattern.match(path)
            if match:
                return route, match.groupdict()
        return None

    def get_all_routes(self) -> List[Route]:
        return list(self._routes)


class LinkRenderer:
    """Renders <Link> components as <a> tags with data-tw-link attributes."""

    @staticmethod
    def render_link(href: str, text: str = "", class_name: str = "") -> str:
        """Render a Link component to HTML."""
        cls = f' class="{class_name}"' if class_name else ""
        return f'<a href="{href}" data-tw-link="{href}"{cls}>{text}</a>'

    @staticmethod
    def render_link_with_attrs(href: str, content: str, attrs: str = "") -> str:
        """Render a Link with additional attributes."""
        extra = f" {attrs}" if attrs else ""
        return f'<a href="{href}" data-tw-link="{href}"{extra}>{content}</a>'


def parse_route_pattern(pattern: str) -> Dict[str, Any]:
    """Parse a route pattern like /blog/[slug] into components."""
    segments = pattern.strip("/").split("/")
    result = {
        "pattern": pattern,
        "segments": [],
        "is_dynamic": False,
        "param_names": [],
    }
    for seg in segments:
        if seg.startswith("[") and seg.endswith("]"):
            param = seg[1:-1]
            result["segments"].append({"type": "param", "name": param})
            result["is_dynamic"] = True
            result["param_names"].append(param)
        else:
            result["segments"].append({"type": "static", "value": seg})
    return result


def match_route(pattern: str, path: str) -> Optional[Dict[str, str]]:
    """Match a URL path against a route pattern. Returns params or None."""
    pattern_segs = [s for s in pattern.strip("/").split("/") if s]
    path_segs = [s for s in path.strip("/").split("/") if s]

    if len(pattern_segs) != len(path_segs):
        return None

    params = {}
    for pseg, useg in zip(pattern_segs, path_segs):
        if pseg.startswith("[") and pseg.endswith("]"):
            params[pseg[1:-1]] = useg
        elif pseg != useg:
            return None
    return params


__all__ = [
    "Router", "Route", "LinkRenderer",
    "parse_route_pattern", "match_route",
]
