"""
Client-side realtime connection for tw/realtime.

Provides a Python-side representation of WebSocket connections
for SSR and build-time analysis. The actual client-side WebSocket
runtime is generated by runtime.py.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional


@dataclass
class RealtimeConnection:
    """Represents a client-side WebSocket connection."""
    path: str
    handlers: Dict[str, List[Callable]] = field(default_factory=dict)
    auto_reconnect: bool = True
    reconnect_delay: float = 1.0
    max_reconnect_delay: float = 30.0

    def on(self, event: str, handler: Callable) -> Callable[[], None]:
        """Register a handler for an event. Returns unsubscribe function."""
        if event not in self.handlers:
            self.handlers[event] = []
        self.handlers[event].append(handler)
        return lambda: self.handlers.get(event, []).remove(handler) if handler in self.handlers.get(event, []) else None

    def to_client_config(self) -> Dict[str, Any]:
        """Serialize connection config for client-side hydration."""
        return {
            "path": self.path,
            "autoReconnect": self.auto_reconnect,
            "reconnectDelay": self.reconnect_delay,
            "maxReconnectDelay": self.max_reconnect_delay,
        }


class RealtimeClient:
    """Manages client-side realtime connections (Python-side representation)."""

    def __init__(self):
        self._connections: Dict[str, RealtimeConnection] = {}

    def connect(self, path: str, **opts) -> RealtimeConnection:
        """Create or get a realtime connection to the given path."""
        if path not in self._connections:
            self._connections[path] = RealtimeConnection(
                path=path,
                auto_reconnect=opts.get("auto_reconnect", True),
                reconnect_delay=opts.get("reconnect_delay", 1.0),
                max_reconnect_delay=opts.get("max_reconnect_delay", 30.0),
            )
        return self._connections[path]

    def get_connections(self) -> Dict[str, RealtimeConnection]:
        return dict(self._connections)

    def get_client_configs(self) -> List[Dict[str, Any]]:
        """Get serializable configs for all connections."""
        return [conn.to_client_config() for conn in self._connections.values()]

    def disconnect(self, path: str) -> None:
        self._connections.pop(path, None)

    def clear(self) -> None:
        self._connections.clear()


__all__ = ["RealtimeClient", "RealtimeConnection"]
