"""
Store implementation for tw/state.

Provides reactive stores with subscriptions, derived state, and cleanup.
This module handles the Python-side store API for SSR and build-time analysis.
The client-side reactive runtime is generated by runtime.py.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional


@dataclass
class Store:
    """A reactive store with subscriptions and derived state support."""
    name: str
    initial_state: Dict[str, Any] = field(default_factory=dict)
    _subscribers: List[Callable] = field(default_factory=list, repr=False)
    _persist: bool = False
    _server_only: bool = False

    def get(self) -> Dict[str, Any]:
        """Return a copy of the current state."""
        return dict(self.initial_state)

    def set(self, new_state: Dict[str, Any]) -> None:
        """Merge new_state into the store and notify subscribers."""
        self.initial_state.update(new_state)
        self._notify()

    def update(self, fn: Callable[[Dict[str, Any]], Dict[str, Any]]) -> None:
        """Apply a function to the state and notify subscribers."""
        self.initial_state = fn(dict(self.initial_state))
        self._notify()

    def subscribe(self, fn: Callable[[Dict[str, Any]], None]) -> Callable[[], None]:
        """Subscribe to store changes. Returns an unsubscribe function."""
        self._subscribers.append(fn)
        return lambda: self._unsubscribe(fn)

    def _unsubscribe(self, fn: Callable) -> None:
        try:
            self._subscribers.remove(fn)
        except ValueError:
            pass

    def _notify(self) -> None:
        state = self.get()
        for fn in self._subscribers:
            try:
                fn(state)
            except Exception:
                pass

    def to_client_config(self) -> Dict[str, Any]:
        """Serialize store config for client-side hydration."""
        return {
            "name": self.name,
            "initialState": self.initial_state,
            "persist": self._persist,
            "serverOnly": self._server_only,
        }


# Global store registry (server-side)
_store_registry: Dict[str, Store] = {}


def create_store(
    name: str,
    initial_state: Optional[Dict[str, Any]] = None,
    persist: bool = False,
    server_only: bool = False,
) -> Store:
    """Create a named global store."""
    store = Store(
        name=name,
        initial_state=initial_state or {},
        _persist=persist,
        _server_only=server_only,
    )
    _store_registry[name] = store
    return store


def get_store(name: str) -> Optional[Store]:
    """Get a registered store by name."""
    return _store_registry.get(name)


def get_all_stores() -> Dict[str, Store]:
    """Return all registered stores."""
    return dict(_store_registry)


def get_client_stores() -> List[Dict[str, Any]]:
    """Return serializable config for all client-accessible stores."""
    return [
        store.to_client_config()
        for store in _store_registry.values()
        if not store._server_only
    ]


def clear_stores() -> None:
    """Clear all stores (for testing)."""
    _store_registry.clear()


class Derived:
    """Derived state from one or more stores."""

    def __init__(
        self,
        deps: List[Store],
        compute: Callable[..., Any],
    ):
        self._deps = deps
        self._compute = compute
        self._cached: Any = None
        self._dirty = True
        self._subscribers: List[Callable] = []

        # Subscribe to dependency changes
        for dep in deps:
            dep.subscribe(self._on_dep_change)

    def get(self) -> Any:
        if self._dirty:
            dep_values = [dep.get() for dep in self._deps]
            self._cached = self._compute(*dep_values)
            self._dirty = False
        return self._cached

    def subscribe(self, fn: Callable[[Any], None]) -> Callable[[], None]:
        self._subscribers.append(fn)
        return lambda: self._subscribers.remove(fn) if fn in self._subscribers else None

    def _on_dep_change(self, _state: Dict[str, Any]) -> None:
        self._dirty = True
        value = self.get()
        for fn in self._subscribers:
            try:
                fn(value)
            except Exception:
                pass


def derived(
    deps: List[Store],
    compute: Callable[..., Any],
) -> Derived:
    """Create derived state from store dependencies."""
    return Derived(deps, compute)


__all__ = [
    "Store", "Derived", "derived", "create_store",
    "get_store", "get_all_stores", "get_client_stores", "clear_stores",
]
