"""
Form and Field implementations for tw/form.

Provides server-side form state management and validation.
The client-side form runtime is generated by runtime.py.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional


@dataclass
class Validator:
    """A field validator."""
    name: str
    message: str = "Invalid value"
    rule: Callable[[Any, Dict], Optional[str]] = None  # Returns error message or None

    def validate(self, value: Any, all_values: Dict[str, Any]) -> Optional[str]:
        if self.rule:
            return self.rule(value, all_values)
        return None


@dataclass
class Field:
    """A form field definition."""
    name: str
    type: str = "text"
    label: str = ""
    placeholder: str = ""
    required: bool = False
    validators: List[Validator] = field(default_factory=list)
    default_value: Any = ""
    async_validator: Optional[str] = None  # URL for async validation


@dataclass
class Form:
    """A form definition with fields, validation, and state."""
    name: str
    action: str = ""
    method: str = "POST"
    fields: List[Field] = field(default_factory=list)
    submitting: bool = False
    errors: Dict[str, str] = field(default_factory=dict)
    values: Dict[str, Any] = field(default_factory=dict)
    touched: Dict[str, bool] = field(default_factory=dict)
    dirty: Dict[str, bool] = field(default_factory=dict)
    step: int = 0  # For multi-step forms
    total_steps: int = 1

    def add_field(self, f: Field) -> None:
        self.fields.append(f)
        self.values[f.name] = f.default_value

    def set_value(self, name: str, value: Any) -> None:
        self.values[name] = value
        self.dirty[name] = True

    def set_touched(self, name: str) -> None:
        self.touched[name] = True

    def validate(self) -> bool:
        """Validate all fields. Returns True if valid."""
        self.errors = {}
        for f in self.fields:
            if f.required and not self.values.get(f.name):
                self.errors[f.name] = f"{f.label or f.name} is required"
                continue
            for validator in f.validators:
                error = validator.validate(self.values.get(f.name), self.values)
                if error:
                    self.errors[f.name] = error
                    break
        return len(self.errors) == 0

    def reset(self) -> None:
        """Reset form to initial state."""
        self.values = {f.name: f.default_value for f in self.fields}
        self.errors = {}
        self.touched = {}
        self.dirty = {}
        self.submitting = False
        self.step = 0

    def next_step(self) -> None:
        if self.step < self.total_steps - 1:
            self.step += 1

    def prev_step(self) -> None:
        if self.step > 0:
            self.step -= 1

    def to_client_config(self) -> Dict[str, Any]:
        """Serialize form config for client-side hydration."""
        return {
            "name": self.name,
            "action": self.action,
            "method": self.method,
            "fields": [
                {
                    "name": f.name,
                    "type": f.type,
                    "required": f.required,
                    "defaultValue": f.default_value,
                    "asyncValidator": f.async_validator,
                }
                for f in self.fields
            ],
            "totalSteps": self.total_steps,
        }


__all__ = ["Form", "Field", "Validator"]
