"""
Data fetching implementation for tw/fetch.

Provides server-side fetch with caching, deduplication, and revalidation.
The client-side fetch runtime is generated by runtime.py.
"""

from __future__ import annotations

import hashlib
import json
import time
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import urllib


@dataclass
class CacheEntry:
    """A cached fetch response."""
    data: Any
    timestamp: float
    ttl: float = 0  # 0 = no expiry


class FetchCache:
    """In-memory fetch cache with TTL and deduplication."""

    def __init__(self):
        self._cache: Dict[str, CacheEntry] = {}
        self._pending: Dict[str, Any] = {}

    def get(self, key: str, ttl: float = 0) -> Optional[Any]:
        """Get cached data if not expired."""
        entry = self._cache.get(key)
        if not entry:
            return None
        if ttl > 0 and (time.time() - entry.timestamp) > ttl:
            return None
        return entry.data

    def set(self, key: str, data: Any, ttl: float = 0) -> None:
        self._cache[key] = CacheEntry(data=data, timestamp=time.time(), ttl=ttl)

    def invalidate(self, key: str = "") -> None:
        if key:
            self._cache.pop(key, None)
        else:
            self._cache.clear()

    def is_pending(self, key: str) -> bool:
        return key in self._pending

    def set_pending(self, key: str, promise: Any) -> None:
        self._pending[key] = promise

    def clear_pending(self, key: str) -> None:
        self._pending.pop(key, None)


# Global fetch cache
_fetch_cache = FetchCache()


def fetch_server(
    url: str,
    *,
    method: str = "GET",
    headers: Optional[Dict[str, str]] = None,
    body: Optional[bytes] = None,
    cache: str = "default",  # default, force-cache, no-store
    revalidate: float = 0,
    timeout: float = 30,
) -> Dict[str, Any]:
    """
    Server-side fetch with caching support.

    cache modes:
      "default"     — use cache if available, otherwise fetch
      "force-cache" — always use cache
      "no-store"    — never cache, always fetch fresh
    """
    cache_key = hashlib.sha256(url.encode("utf-8")).hexdigest()

    # Check cache
    if cache != "no-store":
        cached = _fetch_cache.get(cache_key, ttl=revalidate)
        if cached is not None or cache == "force-cache":
            if cached is not None:
                return cached

    # Deduplication
    if _fetch_cache.is_pending(cache_key):
        return _fetch_cache._pending[cache_key]

    try:
        req = urllib.request.Request(
            url,
            method=method,
            headers=headers or {},
            data=body,
        )
        with urllib.request.urlopen(req, timeout=timeout) as response:
            content_type = response.headers.get("Content-Type", "")
            raw = response.read()
            if "json" in content_type:
                data = json.loads(raw)
            else:
                data = raw.decode("utf-8", errors="replace")

            result = {
                "ok": True,
                "status": response.status,
                "data": data,
                "headers": dict(response.headers),
            }
            _fetch_cache.set(cache_key, result, ttl=revalidate)
            return result
    except Exception as err:
        return {
            "ok": False,
            "status": 0,
            "error": str(err),
            "data": None,
        }


def deduplicate(url: str, fetch_fn) -> Any:
    """Deduplicate concurrent identical fetch requests."""
    cache_key = hashlib.sha256(url.encode("utf-8")).hexdigest()
    if _fetch_cache.is_pending(cache_key):
        return _fetch_cache._pending[cache_key]
    _fetch_cache.set_pending(cache_key, None)
    try:
        result = fetch_fn()
        _fetch_cache.set(cache_key, result)
        return result
    finally:
        _fetch_cache.clear_pending(cache_key)


__all__ = ["FetchCache", "fetch_server", "deduplicate"]
